### ISSUE TITLE
Rename main script to something more natural.

### ISSUE THREAD

**Issue by luis-lavaire** [Nitrux/nitrux-repository-util#15]
The main script in this repo is `nitrux-repository-util.sh`. A more adequate name could be `deploy-pkgs` or `publish-pkgs`.

**Comment by UriHerrera** [comment]
Yes, but need to update _all_ of the rest of the repositories that use it.

**Comment by anupam-git** [comment]
If it is really needed, then it can be done. But if the name is not too much of a problem, can be done later.
Or we can create a copy to not break any existing repositories and carry on renaming little by little.

**Comment by luis-lavaire** [comment]
@anupam-git, it seems good. I'll create a copy of the file and update the other repos accordingly.
