### ISSUE TITLE
Do not drop snapshots during publishLatest()

### ISSUE THREAD

**Issue by anupam-git** [Nitrux/nitrux-repository-util#8]
As of now, `publishLatest()` function deletes if there are any previous snapshots and creates new snapshots.

It should work as follows : 

If the snapshot already exists, create new snapshot with a counter appended at the end. Eg : `snapshot-testing-20180910-1`

**Comment by luis-lavaire** [comment]
@anupam-git, is this still an issue?

**Comment by anupam-git** [comment]
I dont think its still an issues since you've rewritten the script and reconfigured aptly.
