### ISSUE TITLE
Functionality to remove old snapshots

### ISSUE THREAD

**Issue by anupam-git** [Nitrux/nitrux-repository-util#9]
Implement functionality to remove snapshots older than some `DATE`.

**Comment by luis-lavaire** [comment]
@anupam-git, is this still an issue?

**Comment by anupam-git** [comment]
I dont think its still an issues since you've rewritten the script and reconfigured aptly.

**Comment by luis-lavaire** [comment]
Then I guess we should also drop the unneeded scripts.

**Comment by luis-lavaire** [comment]
Is anybody still using the other scripts?

**Comment by luis-lavaire** [comment]
Oops! Seems Uri already removed them. Haha. :sweat_smile:
